<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PlatosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();

        DB::table('platos')->truncate();

        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [1,'CA-1A-001', 1,'Bacalao con Tomate, verdura y patata asada',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [2,'CA-1A-002', 2,'Bacalao con Tomate, verdura y patata asada',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [3,'CA-1A-003', 1,'Berenjena rellena de garbanzos',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [4,'CA-1A-004', 2,'Berenjena rellena de garbanzos',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [5,'CA-1A-005', 1,'Boloñesa de Pollo con Pasta Integral',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [6,'CA-1A-006', 2,'Boloñesa de Pollo con Pasta Integral',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [7,'CA-1A-007', 1,'Bowl de Quinoa con Pollo y Pimiento',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [8,'CA-1A-008', 2,'Bowl de Quinoa con Pollo y Pimiento',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [9,'CA-1A-009', 1,'Chili Vegano',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [10,'CA-1A-010', 2,'Chili Vegano',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [11,'CA-1A-011', 1,'Garbanzos al curry con verduras',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [12,'CA-1A-012', 2,'Garbanzos al curry con verduras',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [13,'CA-1A-013', 1,'Goulash de Ternera',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [14,'CA-1A-014', 2,'Goulash de Ternera',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [15,'CA-1A-015', 1,'Lasaña de Calabacín con Cerdo',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [16,'CA-1A-016', 2,'Lasaña de Calabacín con Cerdo',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [17,'CA-1A-017', 1,'Merluza en Salsa Verde',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [18,'CA-1A-018', 2,'Merluza en Salsa Verde',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [19,'CA-1A-019', 1,'Pimiento relleno de lenteja y espinaca',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [20,'CA-1A-020', 2,'Pimiento relleno de lenteja y espinaca',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [21,'CA-1A-021', 1,'Pollo al ajillo con verdura asada',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [22,'CA-1A-022', 2,'Pollo al ajillo con verdura asada',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [23,'CA-1A-023', 1,'Pollo al Chilindrón',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [24,'CA-1A-024', 2,'Pollo al Chilindrón',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [25,'CA-1A-025', 1,'Pollo al Curry con Verdura y Arroz',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [26,'CA-1A-026', 2,'Pollo al Curry con Verdura y Arroz',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [27,'CA-1A-027', 1,'Pollo al limón + arroz con verduras',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [28,'CA-1A-028', 2,'Pollo al limón + arroz con verduras',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [29,'CA-1A-029', 1,'Pollo Asado con Manzana',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [30,'CA-1A-030', 2,'Pollo Asado con Manzana',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [31,'CA-1A-031', 1,'Pollo con Almendras y Arroz integral',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [32,'CA-1A-032', 2,'Pollo con Almendras y Arroz integral',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [33,'CA-1A-033', 1,'Pollo en Salsa de Calabaza',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [34,'CA-1A-034', 2,'Pollo en Salsa de Calabaza',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [35,'CA-1A-035', 1,'Pollo en Salsa de Tomate con Patata Asada',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [36,'CA-1A-036', 2,'Pollo en Salsa de Tomate con Patata Asada',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [37,'CA-1A-037', 1,'Pollo Guisado con Tomate y Naranja',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [38,'CA-1A-038', 2,'Pollo Guisado con Tomate y Naranja',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [39,'CA-1A-039', 1,'Salmón al horno con patata y verduras',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [40,'CA-1A-040', 2,'Salmón al horno con patata y verduras',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [41,'CA-1A-041', 1,'Solomillo de Cerdo con Salsa de Zanahoria y Patata',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [42,'CA-1A-042', 2,'Solomillo de Cerdo con Salsa de Zanahoria y Patata',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [43,'CA-1A-043', 1,'Espagueti de Calabacín con Boloñesa de Lentejas',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);
        DB::insert('insert into platos (id,codigo,plato_codigo_id,nombre,calorias,plato_peso_id,imagen_1,imagen_2,precio,base_proteina_id,ingredientes,receta) values (?,?,?,?,?,?,?,?,?,?,?,?)', [44,'CA-1A-044', 2,'Espagueti de Calabacín con Boloñesa de Lentejas',0,1,'imagen_1','imagen_2',0,1,'ingredientes','receta']);

        Schema::enableForeignKeyConstraints();
    }
}
