@extends('web.layout.master-wo-menu')
@section('content')
  <x-landing-retos-top-banner/>
  <x-landing-retos-banner/>
  <x-landing-retos-banner-nutricion/>
  <x-landing-retos-steps/>
  <x-landing-retos-banner-acceso/>
  <x-landing-retos-steps-comencemos/>
  <x-landing-retos-banner-dudas/>
@endsection
